### ISSUE TITLE
MBOM

### ISSUE THREAD

**Issue by sweeper240** [ka-moamoa/Practical_SMFC_Design_Guide#2]
Would be nice to include a Bill of Materials as well as recommended hardware sources or alternatives. It's originally suggested that most if not all of the core elements that are needed to make this work are available in a local hardware store.

While the cap and frame might need to be printed... the cathod and anode should probably be sourced and then cut to fit. Same as the use of common clamps/fixations as well as the appropriate position of electrical nodes/wires and the installation (perhaps) of a USB-A input/output as many potential IOT devices might have usb as the primary energy source

**Comment by yebo29** [comment]
According to the video that can be downloaded [here](https://dl.acm.org/action/downloadSupplement?doi=10.1145%2F3631410&file=yen.zip), it requires "wetproofed carbon cloth and carbon felt". I do not know what either of those are nor if they are stocked at hardware stores. In addition, the video mentions:
* A steel flange to fasten these materials to the battery
* RTV silicone for the scaffold
* Undetermined size and length fasteners with nuts

Hopefully the author can add a proper BOM.

**Comment by billyen33** [comment]
Thanks for pointing this out @sweeper240. The bill of material can be found in Appendix A2 of the paper (added this detail in the README of the repository). Links to the specific materials used for this project are also in there. The video demonstrated us constructing a v3 cell, but there is also a v3.1 version (the one in this GitHub) that does not require fasteners or a stainless steel flange.
